name: worki_ui
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

  
dependencies:
  
  qr_flutter:
    git:
      url: git://github.com/lukef/qr.flutter.git
  curved_navigation_bar: ^0.3.2
  awesome_loader: ^0.0.3
  carousel_slider: ^1.4.1
  progress_dialog: ^1.2.1
  datetime_picker_formfield: ^1.0.0
  dropdown_formfield: ^0.1.1
  dropdownfield: ^1.0.3
  intl: ^0.16.1
  firebase_auth: 0.15.3
  google_sign_in: ^4.1.4
  firebase_core: 0.4.4
  flutter_facebook_login: ^1.2.0
  firebase_storage: ^3.1.1
  
  flutter_clean_calendar: ^1.0.1

  flutter_icons: ^1.0.0+1
  pull_to_refresh: ^1.5.8
  lite_rolling_switch: ^0.1.1
  flappy_search_bar: 1.4.1
  file_picker: ^1.3.7
  flutter_shimmer: ^1.2.0
  flutter_read_more_text: ^0.0.1
  flutter_rating_bar: ^3.0.1+1
  flutter_range_slider: "^1.4.0"
  sliding_up_panel: ^1.0.0
  flutter_tindercard: ^0.1.8
  flutter_local_notifications: ^1.4.0
  flutter_picker: ^1.1.3
  charts_flutter: ^0.9.0
  excel: ^1.0.2
  open_file: ^3.0.1

  flutter:
    sdk: flutter
  
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  insta_html_parser: ^0.1.1
  cupertino_icons: ^0.1.2
  firebase_messaging:
  barcode_scan: ^2.0.1
  http: ^0.12.0+4
  enum_to_string: ^1.0.8
  image_picker: ^0.6.3+3
  flutter_map: ^0.8.2
  latlong: ^0.6.1
  geolocator: ^5.3.0
  dbcrypt: ^1.0.0
  cloud_firestore: ^0.13.4+1
  cached_network_image: 2.0.0-rc.1
  google_maps_flutter: ^0.5.24+1
  flutter_google_places: ^0.2.4
  geocoder: ^0.2.1
  horizontal_data_table: ^1.0.5+1
  flutter_polyline_points: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.14.2
  flutter_launcher_icons: "^0.7.3"
  flutter_launcher_name: "^0.0.1"

flutter_icons:
  image_path: "assets/worki_icon.png"
  android: true 
  ios: true

flutter_launcher_name:
  name: "Worki"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/
  - assets/Walkthrough/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
        - asset: assets/fonts/Lato/Lato-Bold.ttf
        
    - family: Trade Winds
      fonts:
        - asset: assets/fonts/Trade_Winds/TradeWinds-Regular.ttf

    - family: Trebuchet
      fonts:
        - asset: assets/fonts/Trebuchet/fonts/TrebuchetMS.ttf
        - asset: assets/fonts/Trebuchet/fonts/TrebuchetMSBold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
